name: Karim Khaled - Docker Image

on:
  workflow_dispatch:

jobs:
  run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_SERVER }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Publish
        run: |
          docker push ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:latest
