name: Karim Khaled - Docker Image

on:
  workflow_dispatch:

jobs:
  run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:${{ github.sha }} .

      - name: Docker Build
        run: |
         echo "Image Tag: ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:${{ github.sha }}"
         docker build -t ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:${{ github.sha }} .

      - name: Docker Publish
        run: |
          docker push ${{ secrets.DOCKER_SERVER }}/${{ secrets.DOCKER_USERNAME }}/karim_khaled:${{ github.sha }}
